// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataACesslayer.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    [Migration("20240724084525_okj")]
    partial class okj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataACesslayer.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "hr-logo.png",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Logo = "it-logo.png",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            Logo = "finance-logo.png",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Logo = "recruitment-logo.png",
                            Name = "Recruitment",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Logo = "employee-relations-logo.png",
                            Name = "Employee Relations",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Logo = "software-development-logo.png",
                            Name = "Software Development",
                            ParentDepartmentId = 2
                        },
                        new
                        {
                            Id = 7,
                            Logo = "it-support-logo.png",
                            Name = "IT Support",
                            ParentDepartmentId = 2
                        },
                        new
                        {
                            Id = 8,
                            Logo = "accounting-logo.png",
                            Name = "Accounting",
                            ParentDepartmentId = 3
                        },
                        new
                        {
                            Id = 9,
                            Logo = "budgeting-logo.png",
                            Name = "Budgeting",
                            ParentDepartmentId = 3
                        },
                        new
                        {
                            Id = 10,
                            Logo = "campus-recruitment-logo.png",
                            Name = "Campus Recruitment",
                            ParentDepartmentId = 4
                        },
                        new
                        {
                            Id = 11,
                            Logo = "corporate-relations-logo.png",
                            Name = "Corporate Relations",
                            ParentDepartmentId = 5
                        });
                });

            modelBuilder.Entity("DataACesslayer.Department", b =>
                {
                    b.HasOne("DataACesslayer.Department", "ParentDepartment")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentDepartmentId");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("DataACesslayer.Department", b =>
                {
                    b.Navigation("SubDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
